### ISSUE TITLE
Releasing the name on PyPI

### ISSUE THREAD

**Issue by oashour** [cberner/darkmagic#8]
Hi Christopher,

Since this package doesn't seem to be used/updated and doesn't actually have any python code at this time, I am wondering if you would be willing to release the name on PyPI? I would like to use it for an [active project](https://github.com/Griffin-Group/DarkMAGIC).

Cheers!

**Comment by oashour** [comment]
I just thought I'd bump this; I cannot find your email or any other contact info on PyPI.

**Comment by oashour** [comment]
Hi Christopher,

Just bumping this one last time since I have no other way to contact you. I didn't want to open a request for the package name on PyPI without trying one last time.

**Comment by cberner** [comment]
Oh sorry, missed your previous message. Actually I still plan to develop this package. Have just been busy finishing up a few other projects

**Comment by oashour** [comment]
No worries thanks! Good luck!
